### ISSUE TITLE
ACE128 Loop

### ISSUE THREAD

**Issue by sharpm2** [arielnh56/ACE128#1]
I'm having an issue with the code from the example to start the loop after the setup instruction. I'm new to Arduino and decided to try this example out. The issue I'm having is when I upload, the LCD displays "Looking for pins" "Turn ACE128". When I turn it nothing changed on the LCD. I have the circuit set up exactly as in the example. Also I do not know much about mapping the pin locations, I think this may be related. Any help is appreciated, thanks!

**Comment by arielnh56** [comment]
What is supposed to happen is that as it sees activity on each pin (up or down) it removes that number from the list. If you aren't seeing that then it isn't seeing activity, or maybe you aren't talking to the PCF8574 at all. (I need to look at the code and see if it is checking for that). This test is a raw pin check - not related to pin mapping.

One thought - are the center pins from your ACE128 grounded? i think that would also cause this symptom.

**Comment by arielnh56** [comment]
Ok, the ACE128test sketch does not actually check if it can talk to the device, which is a fairly obvious oversight on my part, so I think that's probably the most likely issue. Check your object declaration that you have the correct address.

The checked in code is still set for the original MCP23008 chips - address 0x00. The fritzing diagram has the address pins all pulled up which will be 0x27 for the PCF8574 or 0x3F for the PCF8574A

Try changing that to match your circuit.

I'll look at adding a basic chip comm test to the test sketch, and update the test script with an example config line to match the fritzing diagram.

**Comment by sharpm2** [comment]
Thank you I will try this next! Still getting use to changing the code.

**Comment by arielnh56** [comment]
New release posted with added multiturn and eeprom saving capabilities

I also added a basic comm check to the start of the test sketch.. If it is stuck at "looking for ACE-128" then that's your problem.
