### ISSUE TITLE
I2C 0x20 Example Issue

### ISSUE THREAD

**Issue by senorlocksmith** [arielnh56/ACE128#4]
I am trying to test the I2C capability with the correct PCF8574 board, but even when I try to compile the example ino file I get an error of: 

no matching function for call to 'ACE128::ACE128(int, uint8_t*)'

Can anyone explain what is happening? I have not changed or edited the file at all. I would assume it would compile just fine.

**Comment by senorlocksmith** [comment]
I got a reply on Arduino forum and all I had to do was to delete the library and re add it back again and it compiled. Not sure what was hanging it up on compiling but it works now.

**Comment by arielnh56** [comment]
Glad you fixed your issue. I apologise for not seeing it earlier.
