### ISSUE TITLE
cant compile - ACE128pintest

### ISSUE THREAD

**Issue by KaHu85** [arielnh56/ACE128#5]
The Sketch ACE128pintest can not be compiled with Version 2.0.0
Error Message: no matching function for call to 'ACE128::ACE128(int, int, int, int, int, int, int, int, uint8_t*)'

With Version 1.7.0 it works

**Comment by arielnh56** [comment]
please read the comments in the readme about "The following features can be
enabled via uncommenting #defines in the ACE128.h include file:"

People are using them in different ways, so I added flags to keep unused
code out of the compile to reduce the memory footprint.

Alastair Young
alastair@redhunter.com
